### ISSUE TITLE
Schema object reference doesn't look up the reference

### ISSUE THREAD

**Issue by desean1625** [ninofiliu/oa-client#15]
https://spec.openapis.org/oas/v3.1.0#reference-object-example

**Comment by ninofiliu** [comment]
I'm sorry I didn't provide an issue template but what exactly is the issue here?

Can you provide a code with the expected output vs observed input?

If you have the bandwidth, can you provide a PR for a fix that does not break existing tests and adds one that is breaking now and that won't break after your fix? Thanks.

**Comment by desean1625** [comment]
With a simple schema using a ref the schema that is passed into avj isn't the json schema but the link to the reference causing a `Cannot resolve reference` error on validation

```
"responses": {
  "200": {
    "description": "The response",
    "schema": {
      "$ref": "#/components/schemas/user" 
    }
  }
}
```
here is a link to the swagger specification talking about the same thing. 
https://swagger.io/docs/specification/using-ref/

A fix could be using something like [json-ref-paser](https://apitools.dev/json-schema-ref-parser/) to dereference the schema object when you are building the client

**Comment by ninofiliu** [comment]
Thanks for the clarity and the fix suggestion.

This is however [explicitly unsupported](https://github.com/ninofiliu/oa-client?tab=readme-ov-file#3-have-somewhere-your-openapi-specs-as-a-js-object)

> Note that `oa-client` does not resolve specs for you. If you have `$refs`, you should use a package like [json-schema-ref-parser](https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser) to resolve them.

Basically I don't want to take into account the file structure of the codebase of consuming packages. That's the consuming's packages responsibility. I just want to make a lib that takes specs as input and returns a typed helper.

Have a nice day!

**Comment by ninofiliu** [comment]
Also duplicate of #3
